// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.apachee.netty.eighthexample.proto;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.apachee.netty.eighthexample.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_ino = 1;</code>
   * @return The requestIno.
   */
  java.lang.String getRequestIno();
  /**
   * <code>string request_ino = 1;</code>
   * @return The bytes for requestIno.
   */
  com.google.protobuf.ByteString
      getRequestInoBytes();
}
