// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.apachee.netty.eighthexample.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_apachee_netty_eighthexample_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_apachee_netty_eighthexample_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_apachee_netty_eighthexample_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_apachee_netty_eighthexample_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_apachee_netty_eighthexample_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_apachee_netty_eighthexample_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_apachee_netty_eighthexample_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_apachee_netty_eighthexample_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_apachee_netty_eighthexample_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_apachee_netty_eighthexample_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_apachee_netty_eighthexample_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_apachee_netty_eighthexample_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_apachee_netty_eighthexample_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_apachee_netty_eighthexample_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\037com.apachee.netty.eight" +
      "hexample\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"" +
      "\036\n\nMyResponse\022\020\n\010realname\030\002 \001(\t\"\035\n\016Stude" +
      "ntRequest\022\013\n\003age\030\001 \001(\005\":\n\017StudentRespons" +
      "e\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001" +
      "(\t\"`\n\023StudentResponseList\022I\n\017studentResp" +
      "onse\030\001 \003(\01320.com.apachee.netty.eighthexa" +
      "mple.StudentResponse\"$\n\rStreamRequest\022\023\n" +
      "\013request_ino\030\001 \001(\t\"\'\n\016StreamResponse\022\025\n\r" +
      "response_info\030\001 \001(\t2\370\003\n\016StudentService\022r" +
      "\n\025GetRealNameByUsername\022*.com.apachee.ne" +
      "tty.eighthexample.MyRequest\032+.com.apache" +
      "e.netty.eighthexample.MyResponse\"\000\022y\n\020Ge" +
      "tStudentsByAge\022/.com.apachee.netty.eight" +
      "hexample.StudentRequest\0320.com.apachee.ne" +
      "tty.eighthexample.StudentResponse\"\0000\001\022\205\001" +
      "\n\030GetStudentsWrapperByAges\022/.com.apachee" +
      ".netty.eighthexample.StudentRequest\0324.co" +
      "m.apachee.netty.eighthexample.StudentRes" +
      "ponseList\"\000(\001\022o\n\006BiTalk\022..com.apachee.ne" +
      "tty.eighthexample.StreamRequest\032/.com.ap" +
      "achee.netty.eighthexample.StreamResponse" +
      "\"\000(\0010\001B7\n%com.apachee.netty.eighthexampl" +
      "e.protoB\014StudentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_apachee_netty_eighthexample_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_apachee_netty_eighthexample_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_apachee_netty_eighthexample_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_apachee_netty_eighthexample_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_apachee_netty_eighthexample_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_apachee_netty_eighthexample_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_com_apachee_netty_eighthexample_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_apachee_netty_eighthexample_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_apachee_netty_eighthexample_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_com_apachee_netty_eighthexample_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_apachee_netty_eighthexample_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_apachee_netty_eighthexample_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_com_apachee_netty_eighthexample_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_apachee_netty_eighthexample_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_apachee_netty_eighthexample_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_com_apachee_netty_eighthexample_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_apachee_netty_eighthexample_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_apachee_netty_eighthexample_StreamRequest_descriptor,
        new java.lang.String[] { "RequestIno", });
    internal_static_com_apachee_netty_eighthexample_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_apachee_netty_eighthexample_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_apachee_netty_eighthexample_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
